name 'chef-domains'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-domains'
long_description 'Installs/Configures chef-domains'
version '0.1.0'
